# Generated by Django 3.2.9 on 2021-11-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
