# Generated by Django 3.2.9 on 2021-11-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='url',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
